actor:
  actorMaxCount:  10000
  actorMaxClassCount: 100
  actorWorkerCount: 1
  actorMailboxCapacity: 100
  autoSaveTime: 5000

reload:
  enable: true
blade:
  namespace:
    app:
      path: ${ROOT_DIR}/src/Views

redis:
  default:
    host: 'localhost'
    database: 1

session:
  timeout: 3600
  db: default
  sessionStorageClass: 'ESD\Plugins\Session\RedisSessionStorage'
  sessionUsage: 'header'
  headerIdentity: 'sessionId'
  domain: ''
  path: '/'
  httpOnly: true
  secure: false

yii:
  components:
    log:
      traceLevel: 0
      targets:
        - class: 'ESD\Yii\Log\FileTarget'
          levels:
            - error
              - warning
              - info
              - trace
              - profile

    cache:
      class: 'ESD\Yii\Redis\Cache'
      redis:
        database: 2

    formatter:
      sizeFormatBase: 1000

  language: 'zh-CN'
  db:
    default:
      dsn: 'pgsql:host=192.168.108.130;dbname=esd'
      username: 'postgres'
      password: '123456'
      tablePrefix: 'n_'
      poolMaxNumber: 10
      enableSchemaCache: false
      schemaCacheDuration: 3600
      schemaCache: cache


