esd:
  aop:
    excludePaths:
      - src/Libs
      - src/Filters
      - src/Views

  logger:
    level: DEBUG

  profiles:
    active: local

  server:
    name: esd-server
    workerNum: 4
    maxConn: 10240
    debug: false

  port:
    http:
      host: 0.0.0.0
      port: 8080
      openHttpProtocol: true
      sockType: 1